name: uniswap_sdk_dart
description: Uniswap core SDK written in Dart
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  web3dart: ^2.0.0-dev.9
  decimal: ^0.3.5
  http: ^0.12.2
 
  postgres: ^2.2.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
